### ISSUE TITLE
Capistrano::FileNotFound: Cannot change permissions on app/storage

### ISSUE THREAD

**Issue by Arcrammer** [capistrano/laravel#14]
I've run into this problem but I don't know if it's me or a bug. Everything is fine until the point Capistrano tries to change the permissions on `app/storage` in the `releases` directory and I think it's because that file hasn't been created by the time it tries changing the permissions.

Here's the end of the log since the message is raised:
```
ERROR Cannot change permissions: /var/www/Eximius-in-Laravel/releases/20151210144348/app/storage is not a file or directory
cap aborted!
Capistrano::FileNotFound: Cannot change permissions: /var/www/Eximius-in-Laravel/releases/20151210144348/app/storage is not a file or directory
/Users/alexander/.rvm/gems/ruby-2.2.2/gems/capistrano-file-permissions-0.1.1/lib/capistrano/tasks/file-permissions.rake:25:in `block (5 levels) in <top (required)>'
/Users/alexander/.rvm/gems/ruby-2.2.2/gems/capistrano-file-permissions-0.1.1/lib/capistrano/tasks/file-permissions.rake:21:in `each'
/Users/alexander/.rvm/gems/ruby-2.2.2/gems/capistrano-file-permissions-0.1.1/lib/capistrano/tasks/file-permissions.rake:21:in `block (4 levels) in <top (required)>'
/Users/alexander/.rvm/gems/ruby-2.2.2/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `instance_exec'
/Users/alexander/.rvm/gems/ruby-2.2.2/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `run'
/Users/alexander/.rvm/gems/ruby-2.2.2/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => deploy:set_permissions:acl => deploy:set_permissions:check
The deploy has failed with an error: Cannot change permissions: /var/www/Eximius-in-Laravel/releases/20151210144348/app/storage is not a file or directory
** Invoke deploy:failed (first_time)
** Execute deploy:failed
```

Any idea as to what I can do to stop this or why this is happening?

**Comment by zdziczkowski** [comment]
I am having the same problem. Is this a default of using `require 'capistrano/laravel'`? Is there a way to override or disable this task?

**Comment by zdziczkowski** [comment]
This worked!

```
set :file_permissions_paths, [
  'storage',
  'storage/app',
  'storage/framework/cache',
  'storage/framework/sessions',
  'storage/framework/views',
  'storage/logs',
  'vendor',
]
```

**Comment by ikari7789** [comment]
Sorry for the late response. I'll be helping maintain this plugin for the foreseeable future. If any of these issues are still persisting (all of the tickets are quite old), please let me know and I will do what I can to try and help fix things.

**Comment by ikari7789** [comment]
If you're still having trouble, please re-open a new issue.
