### ISSUE TITLE
Deploy issue with Capistrano 3.8

### ISSUE THREAD

**Issue by PaddyLock** [capistrano/laravel#41]
I have the following Gems installed

```
Using rake 12.0.0
Using net-ssh 4.1.0
Using i18n 0.8.1
Using bundler 1.13.6
Using net-scp 1.2.1
Using sshkit 1.13.0
Using airbrussh 1.1.2
Using capistrano 3.8.0
Using capistrano-composer 0.0.6
Using capistrano-file-permissions 1.0.0
Using capistrano-laravel 1.2.1
```

I have the following in my Capfile

```
require "capistrano/setup"
require "capistrano/deploy"
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git
require "capistrano/laravel"
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
```

when I run 

`cap staging deploy --trace `

I get

```
cap aborted!
ThreadError: current thread not owner
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:246:in `mon_check_owner'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:195:in `mon_exit'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:143:in `ensure in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:143:in `require'
/Users/patricklock/Sites/ClickNaomi/Capfile:37:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/Library/Ruby/Gems/2.0.0/gems/capistrano-3.8.0/lib/capistrano/application.rb:14:in `run'
/Library/Ruby/Gems/2.0.0/gems/capistrano-3.8.0/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:23:in `load'
/usr/local/bin/cap:23:in `<main>'
```

Capfile:37:in<top (required)> refers to the line require "capistrano/laravel"

If I remove 

`require "capistrano/laravel"`

from my Capfile I don't have this problem

**Comment by ikari7789** [comment]
Could you please edit this to use 3 ` marks on the new lines please? A single backtick will make it appear inline, 3 backticks makes it a block.

**Comment by PaddyLock** [comment]
thanks, done

**Comment by ikari7789** [comment]
Could you please paste the entire Capfile (edit out anything sensitive if it exists)? It seems the problem is due to line 37? Is that the `require capistrano/laravel` line?

**Comment by ikari7789** [comment]
Are you loading any custom Capistrano tasks of your own?

**Comment by PaddyLock** [comment]
here is the Capfile. Yes #37 is capistrano/laravel
```
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

require "capistrano/laravel"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }

```

And this is my deploy.rb

```
# config valid only for current version of Capistrano
lock "3.8.0"

set :application, "my_project"
set :repo_url, "git@github.com:MyName/My-Project.git"

# Default value for :pty is false
set :pty, true

set :ssh_options, {
  user: 'ubuntu',
  keys: ['~/.ssh/id_rsa'],
  forward_agent: true,
  auth_methods: ["publickey"]
}

# Default branch is :master
# ask :branch, `git rev-parse --abbrev-ref HEAD`.chomp

# Default deploy_to directory is /var/www/my_app_name
set :deploy_to, "/var/www/html"

# Default value for :format is :airbrussh.
# set :format, :airbrussh

# You can configure the Airbrussh format using :format_options.
# These are the defaults.
# set :format_options, command_output: true, log_file: "log/capistrano.log", color: :auto, truncate: :auto

# Default value for :pty is false
# set :pty, true

# Default value for :linked_files is []
# append :linked_files, "config/database.yml", "config/secrets.yml"
append :linked_files, ".env"

# Default value for linked_dirs is []
# append :linked_dirs, "log", "tmp/pids", "tmp/cache", "tmp/sockets", "public/system"
append :linked_dirs, "storage"
```

And staging.rb

```
server 'ec2-12-345-678-90.eu-west-1.compute.amazonaws.com', user: 'ubuntu', roles: %w{app db web}
```

**Comment by ikari7789** [comment]
I've replicated your environment against a VM, and I can't seem to duplicate this problem at all.

**Comment by PaddyLock** [comment]
Do you know what the error message means. Maybe it's a permissions error?

**Comment by PaddyLock** [comment]
I have resolved my issue. I need to upgrade ruby from 2.0.0 to 2.4.0. This also involved updating bundler.
